name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.6.0
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 19
        uses: actions/setup-java@v3.9.0
        with:
          distribution: 'temurin'
          java-version: '19'
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v21
        with:
          repositories: >
            [
              {
                "id": "central",
                "name": "upaio-libs-release",
                "url": "https://upaio.jfrog.io/artifactory/upaio-libs-release"
              },
              {
                "id": "snapshots",
                "name": "upaio-libs-snapshot",
                "url": "https://upaio.jfrog.io/artifactory/upaio-libs-snapshot"
              }
            ]
          servers: >
            [
              {
                "id": "central",
                "username": "info.aguirre.jesus@gmail.com",
                "password": "${{secrets.ARTIFACTORY_TOKEN}}"
              },
              {
                "id": "snapshots",
                "username": "info.aguirre.jesus@gmail.com",
                "password": "${{secrets.ARTIFACTORY_TOKEN}}"
              }
            ]
      - name: Cache SonarCloud packages
        uses: actions/cache@v3.2.2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v3.2.2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze in SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=upa-io_chassis-microservice
      - name: Maven Release
        run: mvn release:prepare release:perform -B -s /home/runner/.m2/settings.xml -DreleaseVersion=${{ github.event.inputs.releaseVersion }} -DdevelopmentVersion=${{ github.event.inputs.developmentVersion }}
        env:
          CI_DEPLOY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          CI_DEPLOY_PASSWORD: ${{ secrets.ARTIFACTORY_TOKEN }}
